logger:
  #Level 0 紧急的 1警报 2重要的 3错误 4警告 5提示 6信息 7调试
  consoleShow: true
  consoleLevel:  7
  fileWrite:  false
  fileLevel:  7
  multiFileWrite: false
  multiFileLevel: 7

rpcServer:
  serverName: "authorize"
  registerPlugin: "etcd"
  registerServers:
    - "127.0.0.1:2379"
  basePath: "go-admin-example"
  addr: ""
  port: 8899
  pprof: 18899

db:
  dbType: "mysql"
  maxOpenConn: 20
  maxIdleConn: 4
  maxIdleTime: 100
  maxLifeTime: 3600
  level: 4
  slowThreshold: "100ms"
  master:
    user: "root"
    password: "starunion"
    host: "127.0.0.1"
    port: "3306"
    database: "go-admin"
  slave:
    - user: "root"
      password: "starunion"
      host: "127.0.0.1"
      port: "3306"
      database: "go-admin"

redis:
  redisType: "alone"
  startAddr: ["127.0.0.1:6379"]
  active: 100
  idle: 100
  auth: ""
  connTimeout: "100ms"
  readTimeout: "100ms"
  writeTimeout: "100ms"
  idleTimeout: "100ms"

tracer:
  openTrace: true
  traceName: "authorize"
  host: "127.0.0.1:6831"

captcha:
  length: 6
  strType: 3
  bkgColors:
    - B: 255
      A: 255
