stages: # 分段
  - deploy

deploy-job:
  stage: deploy
  script:
    - cd authorize
    - docker build -t authorize .
    - if [ $(docker ps -aq --filter name= authorize) ]; then docker rm -f authorize;fi
    - docker run -d
